[project]
name = "est-alan-scheduler"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.7",
]

[tool.setuptools]
packages = ["est_alan_scheduler"]

[project.scripts]
est-alan-scheduler = "est_alan_scheduler.main:main"
